# Offense count: 2
# Configuration parameters: .
# SupportedStyles: annotated, template, unannotated
Style/FormatStringToken:
  EnforcedStyle: unannotated

# Offense count: 2
# Cop supports --auto-correct.
Style/IfUnlessModifier:
  Exclude:
    - 'flt2png.rb'

# Offense count: 2
# Cop supports --auto-correct.
Style/ParallelAssignment:
  Exclude:
    - 'flt2png.rb'

# Offense count: 2
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, ConsistentQuotesInMultiline.
# SupportedStyles: single_quotes, double_quotes
Style/StringLiterals:
  Exclude:
    - 'flt2png.rb'
